name: 'TypeScript Migration'
description: 'Tracks a TypeScript migration by a given source folder'
inputs:
  source-folder:
    description: 'Source folder'
    required: true
    default: 'src'
  base-branch:
    description: 'Base branch'
    required: true
    default: 'main'
  title:
    description: 'Custom issue title'
    required: true
    default: 'TypeScript Migration'
runs:
  using: 'node16'
  main: 'dist/index.js'
